name = "personal-website"
compatibility_date = "2025-07-22"
preview_urls = true
workers_dev = true
routes = [{ pattern = "new.abhishe.com", custom_domain = true }]

[assets]
directory = "./dist"
not_found_handling = "404-page"
